site_name: H2O Health Documentation

theme:
  name: material
  logo: assets/h2o_logo/h2oai.png
  favicon: assets/h2o_logo/favicon.ico
  font:
    text: Roboto
  features:
    - navigation.top
    - search.suggest
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/weather-night
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
  plugins:
    - search
extra:
  version:
    provider: mike



markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css


plugins:
  - search
  - macros


copyright: Copyright Â© 2022 H2O.ai. All rights reserved


nav:
    - Home: 'index.md'
    - 'Access H2O Health Apps': 'access_h2o_health_apps.md'
    # - 'What is H2O Health?': 'what_is_h2o_health.md'
    # - 'Suites': 'suites.md'
    # - 'FAQ': 'faq.md'
    - CHOS: 
        - 'Overview': 'epidemiology/covid_19_hospital_occupancy_simulator/overview.md'
        - 'Guide': 
          - 'How do simulations work?': 'epidemiology/covid_19_hospital_occupancy_simulator/how_do_simulations_work.md'
          - 'Simulation Settings': 'epidemiology/covid_19_hospital_occupancy_simulator/simulation_settings.md'
          - 'Models': 'epidemiology/covid_19_hospital_occupancy_simulator/models.md'
          - 'Charts': 'epidemiology/covid_19_hospital_occupancy_simulator/charts.md'
          - 'Data Files': 'epidemiology/covid_19_hospital_occupancy_simulator/data_files.md'
        - 'Terminology': 'epidemiology/covid_19_hospital_occupancy_simulator/terminology.md'
        #- 'Release Notes': 'epidemiology/covid_19_hospital_occupancy_simulator/release_notes.md'
        - 'Team': 'epidemiology/covid_19_hospital_occupancy_simulator/team.md'
        - 'FAQ': 'epidemiology/covid_19_hospital_occupancy_simulator/faq.md' 
    - 'Team': 'team.md'
    



 




        
  
        


